### ISSUE TITLE
Request for More Details on PS Move Controller Teleoperation

### ISSUE THREAD

**Issue by yu-jinh** [ir-lab/bimanual-imitation#3]
Hi there!

First of all, thank you for your incredible work! I’m currently building a teleoperation system for MuJoCo simulation with my robot and was really impressed by the implementation of the PS Move controllers shown on your website.

I was wondering if you could share more details about the teleoperation setup using the PS Move controllers. Specifically, I’m curious whether the teleoperation was implemented from scratch or if there are any existing repositories or tools that might simplify the process.

Thanks again for your help and for the great work!

**Comment by mdrolet01** [comment]
Hello,

Please see the following file for our PS Move API interface:
https://github.com/ir-lab/irl_control/blob/master/irl_control/input_devices/ps_move.py

I used the following library to setup the controllers:
https://github.com/thp/psmoveapi

I built this library and then added it to my path for python (see the top of the python script above).
I hope this helps :)

Best,
Michael

**Comment by yu-jinh** [comment]
Hello Michael,

Thank you so much for your response and for providing the links! This is incredibly helpful and exactly what I needed. Really appricate you time for the guidance!

**Comment by mdrolet01** [comment]
@yu-jinh No problem! Glad I could help.
