### ISSUE TITLE
Source files of NIST model

### ISSUE THREAD

**Issue by zichunxx** [ir-lab/bimanual-imitation#4]
Hi! 

I want to apply the methods mentioned in your paper to the real robot. 

So, I need to 3D print the male and female NIST models. However, based on the required open width to grab the NIST model, it seems that the size of your NIST model is different from the model I get from this [web](https://www.nist.gov/el/intelligent-systems-division-73500/robotic-grasping-and-manipulation-assembly/assembly). 

Would you mind sharing your source model file? These separate STL files are hard to print. 

Thanks for your time!

**Comment by mdrolet01** [comment]
Hi,

Unfortunately, I don't recall the website I got the CAD model from, but I believe I scaled it down in blender. The NIST model is very tedious to change, but you might find the VHACD library useful to decompose the stl you found:
https://github.com/kmammou/v-hacd

Best,
Michael
