### ISSUE TITLE
Issue with iris drivers

### ISSUE THREAD

**Issue by ssvision** [ir-lab/bimanual-imitation#5]
When executing the script as stated in the README section after proper activation and installation of environments I got the following error when I ran python bimanual_quad_insert.py 

ibGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:$${ORIGIN}/dri:/usr/lib/dri, suffix _dri) libGL error: failed to load driver: iris libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:$${ORIGIN}/dri:/usr/lib/dri, suffix _dri) libGL error: failed to load driver: iris libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:$${ORIGIN}/dri:/usr/lib/dri, suffix _dri) libGL error: failed to load driver: swrast

I got the same error while running python imitate_<algorithm>.py as well after a few seconds of code execution.

I fixed the error by writing the below command in my bashrc file
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6

Turns out there is an issue with anaconda conda manager and the required files for graphics particularily libstdc++.so.6 when run under the conda env, exctracts it from the conda base not the system base which causes the issue.

Requesting maintainers of this repo to add this useful info. TIA

**Comment by mdrolet01** [comment]
Hi, thanks for bringing this up. This repo only provides a basic pip/conda package list (as many people have a different OS or package manager), so users can set up the environment as they prefer.
